### ISSUE TITLE
Warnings from Swift 5.2 compiler

### ISSUE THREAD

**Issue by timbms** [cezheng/Fuzi#106]
### Description:
* Have a no warning when compiling

* Actual behaviour:
Swift 5.2 included in Xcode Version 11.4 beta (11N111s) reports 2 warnings:
1. In Queryable.swift
       ` var prefixChars = [CChar]()`
> Initialization of variable 'prefixChars' was never used; consider replacing with assignment to '_' or removing it

2. In Document.swift
```
 public convenience init(cChars: [CChar]) throws {
    try self.init(buffer: UnsafeBufferPointer(start: UnsafePointer(cChars), count: cChars.count))
  }
```
> Initialization of 'UnsafePointer<CChar>' (aka 'UnsafePointer<Int8>') results in a dangling pointer

and also gives instructions on how to address: 
> 1. Implicit argument conversion from '[CChar]' (aka 'Array<Int8>') to 'UnsafePointer<CChar>' (aka 'UnsafePointer<Int8>') produces a pointer valid only for the duration of the call to 'init(_:)'
> 2. Use the 'withUnsafeBufferPointer' method on Array in order to explicitly convert argument to buffer pointer valid for a defined scope
> 

### Environment
* Package Manager:
	- [ ] Carthage, version:
	- [x] CocoaPods, version: 1.9.0.beta.2
	- [ ] Manually

* Fuzi version: 3.1.1
* Xcode version: Version 11.4 beta (11N111s) 

### How to reproduce:
Integrate project

**Comment by cezheng** [comment]
Thank you! Fixed in release [3.1.3](https://github.com/cezheng/Fuzi/releases/tag/3.1.3).
