### ISSUE TITLE
HTMLDocument is not ready immediately

### ISSUE THREAD

**Issue by gazsiazasz** [cezheng/Fuzi#111]
### Description:
If I run the code below, sometimes it can not do the three xpath lookup, however the `data` can be dumped, and it contains a valid HTML.

* Expected behaviour:
firstChild(xpath: ).stringValue returns a valid value
* Actual behaviour:
firstChild(xpath: ).stringValue returns nil

Frequency: 3/10

### Environment
* Package Manager:
	- [ ] Carthage, version:
	- [ ] CocoaPods, version:
	- [ x ] Manually

* Fuzi version: 3.1.2
* Xcode version: Version 12.0 beta 4 (12A8179i)

### How to reproduce:

```
    func parse(html: HTMLDocument) {
        let ads = html.xpath("//li[@data-uadid]")
        ads.forEach {
            if let data = try? Data(contentsOf: URL(string: $0.xpath(".//div[@class='uad-title']//a/@href").first!.stringValue)!) {
                let product = Product()
                let ad = try! HTMLDocument(data: data)
                product.product_id = ad.firstChild(xpath: "./@data-uadid")?.stringValue
                product.name = ad.firstChild(xpath: ".//div[@class='uad-title']//a/text()")?.stringValue
                product.url = ad.firstChild(xpath: ".//div[@class='uad-title']//a/@href")?.stringValue
                if let url = product.url {
                    print(url)
                } else {
                    print(product.product_id)
                    print($0.rawXML)
                }
            }
        }
    }
```

**Comment by gazsiazasz** [comment]
false alarm

**Comment by mlch911** [comment]
how did you fix this? I'm encounter the same issue

**Comment by mlch911** [comment]
In case anyone else gets the same error in the future, this error is because cNode memory may be freed. 
You must access the required properties when generating XMLElement.
