### ISSUE TITLE
Fuzi behaving different in debug and release build, sometimes crash

### ISSUE THREAD

**Issue by kukushi** [cezheng/Fuzi#112]
### Description:
* Expected behavior:
Fuzi behaving the same in debug build and release build.

* Actual behavior:
Starting from Xcode 11.4, Fuzi behaving differently in debug and release build, sometimes crashes.
In my other project, the `pointee.next` always access an invalid address and crashed. Maybe some changes in the libxml2 cause this issue.

### Environment
* Package Manager:
	- [x] Carthage, version: 3.1.3
	- [ ] CocoaPods, version:
	- [ ] Manually

* Fuzi version: 3.1.3
* Xcode version: 11.4 - 12.0 Beta

### How to reproduce:

I have an example for reproducing this issue: https://github.com/kukushi/FuziCrash

**Comment by lyricdon** [comment]
I run into this issue too,   the method 'xmlGetProp' crashed with 'EXC_BAD_ACCESS'.
Have you resolve this?

**Comment by kukushi** [comment]
During the process of creating a minimum swift file for reproducing this issue, I found it was a crash caused by an inappropriate usage of `unowned let` and referencing a released object inside the third party framework. The weird part is that crash only happened in the release build. Anyway, this is not a issue of libxml and I will close this issue.
