### ISSUE TITLE
Swift 2.2 Master Release? 

### ISSUE THREAD

**Issue by razvandub** [cezheng/Fuzi#12]
Hi, 

When do you plan to release a (up-to-date) Swift 2.2 version with no warnings? 

Thanks.

**Comment by cezheng** [comment]
@razvandub 
Hi, I think I'm gonna do it right away.

But the current master branch still have 2 warnings which were left alone in order to keep the build compatibility with Swift 2.1.

**Comment by cezheng** [comment]
Shame that I don't know if there's a preprocessing define in Swift that can tell whether current Swift compiler is 2.1 or 2.2.

FYI. Current warnings on Swift 2.2:
https://github.com/cezheng/Fuzi/blob/65bcf1b63170dc81dbe6b718f3ab9f34e4341c8f/Fuzi/Helpers.swift#L81
https://github.com/cezheng/Fuzi/blob/65bcf1b63170dc81dbe6b718f3ab9f34e4341c8f/Fuzi/NodeSet.swift#L41

**Comment by razvandub** [comment]
@cezheng Thanks. See e.g., "#if swift(...)" in https://developer.apple.com/library/mac/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html#//apple_ref/doc/uid/TP40001051.

**Comment by cezheng** [comment]
@razvandub Thanks :smile:  That's exactly what I've been looking for. 

Just before I saw your reply, I released 0.3.1 with most Swift 2.2 warnings removed. I think I will try this in my next release though.

**Comment by razvandub** [comment]
Np, thanks.

**Comment by cezheng** [comment]
@razvandub 
Sadly this #if swift(...) won't even compile with xcode 7.2. I guess I'm leaving these warning alone until Swift 3. Closing this issue for now.
https://travis-ci.org/cezheng/Fuzi/jobs/119739931

**Comment by razvandub** [comment]
@cezheng Have you tried "osx_image: xcode7.3"?

**Comment by cezheng** [comment]
@razvandub xcode7.3 will definitely work since I ran the tests on my macbook. I set it to 7.2 just because I don't want to break the build compatibility with xcode 7.2 yet.

**Comment by cezheng** [comment]
But I wonder how this piece of sample code works for Swift 1.0 when it just won't compile on Swift 2.1

```
#if swift(>=2.2)
  print(“Hello!”)
#elseif swift(1.0)
  println(“Hello!”)
#else
  This code will not parse or emit diagnostics
#endif
```
