### ISSUE TITLE
css attribute selector

### ISSUE THREAD

**Issue by Progeny** [cezheng/Fuzi#14]
It seems query on attributes are not working:

let x = tr.firstChild(css: "td[attribute=value]")?.stringValue

is returning a wrong value (the one of the 1st TD, not the one that should be matched by attribute=value)

**Comment by cezheng** [comment]
Hi, thanks for reporting. I would appreciate it if you could provide the html source and the query you use to find out what happens

**Comment by Progeny** [comment]
`<table class="dataTable"><tr><td headers="attr1">asd</td></tr><tr><td headers="attr2">asd2</td></tr></table>`

if let table = doc.firstChild(css: "table.dataTable") {
for tr in table.css("tr") {
let x = tr.firstChild(css: "td[headers= attr2]")?.stringValue
}
}

x would be always "asd" instead of "asd2"

**Comment by Progeny** [comment]
my fault, sorry.
