### ISSUE TITLE
Can I import this into my Objective-C project?

### ISSUE THREAD

**Issue by objcchobo** [cezheng/Fuzi#17]
Thanks for the great library! I am using Ono and AFOnoResponseSerializer (https://github.com/AFNetworking/AFOnoResponseSerializer) but I found it doesn't work well for some CSS selectors even though they are not that complex. For example, even "h1.title" or ".highlighted .itemImg .img" do not seem to work. Does Fuzi work for these CSS selectors? If so, is there a way to import Fuji in my Objective-C project and work with AFOnoResponseSerializer? Thanks!

**Comment by cezheng** [comment]
Sorry, Fuzi can only be used in Swift projects. For objc projects please stick to Ono

**Comment by objcchobo** [comment]
@cezheng Thanks for the quick clarification! I saw you found some bugs in Ono and fixed them. Do you still have the change list?

**Comment by cezheng** [comment]
@objcchobo I did fixed some bugs related to memory leaks, error handling and CSS selectors, but the one related to CSS was on id selectors, and I believe the examples you mentions should work with both Ono and Fuzi.

If Ono did failed to work with these selectors, maybe sharing the HTML document you are dealing with, along with your code, may help finding out what went wrong.

**Comment by objcchobo** [comment]
@cezheng What I want to do is to extract info from the URL http://m.newegg.com/Product/index?itemnumber=9SIA3782WV7397 using two CSS selectors:
- ".price-current": it's expected to return "$1,194.95" (string value) but for some reason, it returns "\r\n        \r\n\t\t\r\n        \r\n            \r\n                    \r\n            $1,198.00\r\n            \r\n                –\r\n                \r\n            \r\n            \r\n        \r\n    "
- ".swiper-slide-visible .imgWrap img": it's expected to return <img> element but it seems Ono can't find it 
Thanks a lot for the help!

**Comment by cezheng** [comment]
I haven't tried it with Ono yet, but for Fuzi

* ".price-current" this one is working
* ".swiper-slide-visible .imgWrap img" this one is not. And I looking into the html source, but didn't find anything with class `swiper-slide-visible` or `imgWrap`

**Comment by cezheng** [comment]
For Ono, ".price-current" is working too

**Comment by objcchobo** [comment]
Thanks a lot! It seems that the 'swiper-slide-visible' is added by JavaScript after the page is loaded and that's probably why Ono couldn't find it. BTW, for the first item, do you mean Ono returns "$1,194.95" instead of "$1,198.00"?

**Comment by cezheng** [comment]
@objcchobo 
If you download the html and search 'price-current' in it, you can only find 2 elements, the first one is 1198 and the second one is 1199. So I guess it is working correctly

**Comment by objcchobo** [comment]
Thanks a lot! I was using Chrome's Inspector to look at the html and that's why I saw elements which are added later. When I used wget, I got the same result. Now I finally figured out:) BTW, can you please let me know what the memory leak bug was so that I can fix it? Thanks!

**Comment by objcchobo** [comment]
@cezheng Sorry about too many questions. Does Fuji support CSS selector like meta[property='og:image'] ? It seems Ono doesn't work with it.

**Comment by cezheng** [comment]
CSS support in Fuzi/Ono is not comprehensive, and I guess they don't support the selector you mentioned. However, since libxml2 itself doesn't support CSS selector, all Fuzi/Ono does is just converting CSS Selectors to XPath queries and then execute the XPath.

So if certain CSS selector is not currently supported, you can directly write the XPath query to do the job.

For your case, you can use the XPath `//meta[@property='warning']`

**Comment by cezheng** [comment]
For memory leak problem, you should call `xmlXPathFreeObject` for every return value(xmlXPathObjectPtr) of the [`xmlXPathObjectPtrWithXPath`](https://github.com/mattt/Ono/blob/master/Source/ONOXMLDocument.m#L851) method after you finish using them. There're 2 places that use it.
https://github.com/mattt/Ono/blob/master/Source/ONOXMLDocument.m#L757

For Fuzi, it has kinda different class design, it wraps `xmlXPathObjectPtr` into a class and release it in deinit. https://github.com/cezheng/Fuzi/blob/master/Fuzi/Queryable.swift#L102

**Comment by objcchobo** [comment]
Thanks a lot for the quick and detailed clarification! Regarding the memory leak issue, I just added 
- xmlXPathFreeObject(XPath);    in L352
- xmlXPathFreeObject(xmlXPath);    in L772
Does these look OK? Thanks!

**Comment by cezheng** [comment]
**xmlXPathFreeObject(XPath); in L352** 
I guess this one is not correct.
You can treat [`ONOXPathEnumerator`](https://github.com/mattt/Ono/blob/master/Source/ONOXMLDocument.m#L157) the same as [`XPathNodeSet`](https://github.com/cezheng/Fuzi/blob/master/Fuzi/NodeSet.swift#L106) in Fuzi. the xmlXPathObjectPtr is needed by the `ONOXPathEnumerator` until being released so you should put `xmlXPathFreeObject` in `ONOXPathEnumerator`'s `dealloc`.

**xmlXPathFreeObject(xmlXPath); in L772**
This one looks good to me.

**Comment by cezheng** [comment]
@objcchobo 
Ahh, sorry. It is already there.
https://github.com/mattt/Ono/blob/master/Source/ONOXMLDocument.m#L189

I guess since it is kinda a long time ago when I fixed the bug, and almost forgot all about it. The `ONOXPathEnumerator` does not have a memory leak. The leak just lies in `functionResultByEvaluatingXPath:`. Just add `xmlXPathFreeObject(xmlXPath); in L772` and it is all fixed.

**Comment by objcchobo** [comment]
@cezheng Thanks a lot for correcting me and giving me all the details! I learned a lot:)
