### ISSUE TITLE
Redefinition of module 'libxml2' error when using framework that uses Fuzi

### ISSUE THREAD

**Issue by daehn** [cezheng/Fuzi#21]
I run into an issue using Fuzi via Carthage and two nested frameworks.
Framework A has a Carthage dependency to Fuzi and is itself a carthage dependency of framework B.
Building framework A works fine, however framework B ends up with 2 module maps and a redefinition of libxml2 (as Fuzi is contained in framework A and as a resolved dependency pulled into B). I don't have much experience using module maps, so this might very well be an error on my side or maybe an Carthage issue.

**Comment by cezheng** [comment]
@daehn Hi, thanks for reporting the issue.

This is how Fuzi's module map for libxml2 look like: https://github.com/cezheng/Fuzi/blob/master/libxml2/module.modulemap

I think framework B might also have defined a module map with name 'libxml2', which mean a better practice for defining libxml2 is to name the module as something like `FuziLibxml2` to avoid name conflict.

**Comment by daehn** [comment]
Hi @cezheng, thanks for the fas reply. I checked and A and B don't define any module maps. I created an issue for carthage as well: https://github.com/Carthage/Carthage/issues/1383

**Comment by cezheng** [comment]
@daehn 
Hi, I have created 3 projects to try to reproduce your problem, but everything seems to be working alright. So I guess you might have some misconfiguration in your project.

Xcode version: 7.3.1
Carthage version: 0.17.2

Framework A: https://github.com/cezheng/FrameworkThatUsesFuzi
Framework B: https://github.com/cezheng/FrameworkWithDepThatUsesFuzi
App that uses Framework B: https://github.com/cezheng/AppWithDepWhoesDepUsesFuzi

**Comment by cezheng** [comment]
Hi @daehn , have you find out what caused the problem yet? I'm just curious about why this happens though.

**Comment by daehn** [comment]
Hey @cezheng, I did not find the cause of the issue yet, but it does not happen to me if I attach a binary to the release of Fuzi instead of carthage checking it out and building it locally.

**Comment by odonckers** [comment]
Hi, this issue is back as of Swift 4.1 (Xcode 9.3). I rely on this module, so it would be very much appreciated if this was resolved quickly.

**Comment by dan12411** [comment]
same issue as https://github.com/tid-kijyun/Kanna/pull/177, I temporary change the "libxml2" to "libxmlFuzi" locally, and build without error

**Comment by odonckers** [comment]
@dan12411 I did the same thing, and it works like normal now.

**Comment by AshishMultitv** [comment]
change the "libxml2" to "libxmlFuzi" locally , for fix this problem
