### ISSUE TITLE
rawXML self-closes empty tags

### ISSUE THREAD

**Issue by laurent-humbert** [cezheng/Fuzi#23]
rawXML self-closes empty tags, this can cause problems (with frames in my case)

I've changed this function to look like that, and it seems to have fixed the problem

#import <libxml2/libxml/xmlsave.h>  (in libxml2-fuzi.h)

 public private(set) lazy var rawXML: String = {
    let buffer = xmlBufferCreate()
    let ctxt = xmlSaveToBuffer(buffer, nil, Int32(XML_SAVE_NO_EMPTY.rawValue))
    xmlSaveTree(ctxt,self.cNode)
    xmlSaveClose(ctxt)
    let dumped = ^-^xmlBufferContent(buffer) ?? ""
    xmlBufferFree(buffer)
    return dumped
  }()

**Comment by cezheng** [comment]
Hi @laurent-humbert 
Thanks for reporting the issue. I'm not sure what you mean by `rawXML self-closes empty tags`, could you give me an example?

**Comment by laurent-humbert** [comment]
For example it turns

<iframe allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" width="690" height="354" src="http://video-api.wsj.com/api-video/player/iframe.html?guid=72D0C42F-A1E3-4DAA-AC40-D24321E07A9C"></iframe>

into

<iframe allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" width="690" height="354" src="http://video-api.wsj.com/api-video/player/iframe.html?guid=72D0C42F-A1E3-4DAA-AC40-D24321E07A9C"/>

and if you use a strict browser like Safari, it will fail to parse what's after the iframe

**Comment by laurent-humbert** [comment]
It turns
`<iframe src="..."></iframe>`
into
`<iframe src="..."/>`

**Comment by cezheng** [comment]
@laurent-humbert It seems I didn't realize Ono treats XML and HTML the same way. Have you tried `htmlNodeDump` instead of `xmlNodeDump`?

**Comment by laurent-humbert** [comment]
er... no, to be honest I'm not familiar at all with libxml2

**Comment by cezheng** [comment]
OK, let me take a look

**Comment by cezheng** [comment]
@laurent-humbert 
I have updated the master branch to use htmlNodeDump for Nodes in an HTMLDocument and it seems to have solved the problem. See if this resolves your problem.

Note that XMLDocument's behavior remains unchanged.

**Comment by laurent-humbert** [comment]
Yes that seems to have done the trick too. Thanks!

**Comment by laurent-humbert** [comment]
Oops, upgraded to the latest version and it seems there's a problem. isHTML returns false for HTML nodes and rawXML calls xmlNodeDump instead of htmlNodeDump.
