### ISSUE TITLE
Root Element with attributes not working

### ISSUE THREAD

**Issue by Ajayiosdeveloper** [cezheng/Fuzi#25]
Hi Team,

              Its good using the FUZI.I am having a problem when my xml document's root element having attributes then its not working.

When i removed the attributes in the root element. Its a charm.Giving the desired results.

Please tell me the solution for doing this.

**Comment by cezheng** [comment]
Hi @Ajayiosdeveloper , would you please provide the code you're using & the document you had problem dealing with, to let me see how `its not working`? Thanks

**Comment by Ajayiosdeveloper** [comment]
[web.txt](https://github.com/cezheng/Fuzi/files/380923/web.txt)

the above is my xml document

and the code i am using is shared below,

 let xmlString = try! String(contentsOfFile: NSBundle.mainBundle().pathForResource("web", ofType: "xml")!, encoding:NSUTF8StringEncoding)
            
         let parser = SSSXMLFileReader()
        
         parser.initXml(xmlString)


    func initXml(xml:String){
        
        self.xmlString = xml
    }

  try parser.getValue("//web/name")

func getValue(xPath:String)throws->String{
        
        if let doc = try? XMLDocument(string: xmlString) {
       
        if let value = getValueFrom(doc,xPath: xPath){
        
            return value
        }
        else{
            
             throw ParseError.XPathError
            
            }
       }
        
        return ""
    }


func getValueFrom(doc:XMLDocument,xPath:String)->String?{
        
        if doc.xpath(xPath).count > 0 {
            
            print(doc.xpath(xPath).first!)
            
            return doc.xpath(xPath).first!.stringValue
        }
           return nil
    }

Thanks for your early response.i really appreciate the work for FUZI.

**Comment by Ajayiosdeveloper** [comment]
All the code works really well if there are no attributes for the root element but if there nothing works.

**Comment by cezheng** [comment]
Hi @Ajayiosdeveloper 
Your xpath query is not working because you have a default namespace defined for you document. To make it work

```swift
// you can choose a different prefix than "ns"
doc.definePrefix("ns", defaultNamespace: "http://www.swift.org/SwiftWebConfig")
```

and change your query to `"//ns:web/ns:name"`

FYI, http://stackoverflow.com/questions/3135175/libxml2-error-with-namespaces-and-xpath

**Comment by Ajayiosdeveloper** [comment]
Thank you Cezheng. Its working now.

**Comment by matt-curtis** [comment]
What do you think about adding something to the README indicating this? Maybe suggesting use of `local-name()='tag'` as an alternative?

**Comment by cezheng** [comment]
@matt-curtis 
I've never used that so I'm not sure. Do you have an example?

**Comment by matt-curtis** [comment]
You can use `/*[local-name()="head"]` and `/*[name()="mynamespace:head"]` to handle namespaces without registering them. `local-name()` ignores the namespace of an element, and selects for just the tag. `name()` allows you to specify the namespace and the tag together, treating the tag and namespace as only strings.

**Comment by cezheng** [comment]
@matt-curtis 
For the example in this issue, what would the query be?

Is it
`"//ns:web/ns:name"` -> `//*[local-name()="web"]/*[local-name()="name"]`?

The it seems registering a prefix for the namespace yields a shorter query

**Comment by matt-curtis** [comment]
You're right, registering the namespace does yield a shorter query, I was just suggesting possible options. There's also `/*[name()="ns:web"]/[name()="ns:name"]` that you can use.

**Comment by cezheng** [comment]
@matt-curtis 
Thanks for the advice. I guess I will add something like FAQ when I get some free time.
