### ISSUE TITLE
FUZI support for Swift 3

### ISSUE THREAD

**Issue by Ajayiosdeveloper** [cezheng/Fuzi#26]
Hi Cezheng,

                    We team needed to use FUZI for Swift 3 and in present development on Xcode beta 8.3.Its working all well on  Swift 2.2 but when developed for Swift 3 and Xcode Beta 8.3 having many errors.

                   Is there any official update from your end for supporting Swift 3 ? If not the case , what i can do for make use of FUZI for Swift 3?

                  Also more importantly to note that we are going to use FUZI for parsing on Linux environment also. Will this work? is there any solution for making this work on Linux too ? are there any dependencies to add ? Please guide me using FUZI in this context.

                  Thanks for the Library.and the Team.

**Comment by cezheng** [comment]
Hi @Ajayiosdeveloper ,
please use the swift-3 branch for Xcode 8 beta. It is currently updated for Xcode 8 beta 3.

For linux, that would require Apple's Foundation on Linux to be usable since Fuzi relies on it. I have tried a few months before but didn't work out. See this issue #7

**Comment by Ajayiosdeveloper** [comment]
Hi, i am using Cocoa pods. How can i get that Swift-3 branch using cocoa pods?

**Comment by cezheng** [comment]
@Ajayiosdeveloper Please refer to the [Podfile syntax reference](https://guides.cocoapods.org/syntax/podfile.html).

**Comment by cezheng** [comment]
For Swift 3 related comments, go to #27 
For Linux & SPM discussion, go to #7 
Closing this issue.
