### ISSUE TITLE
Update for Xcode 8 beta 6 / Swift 3.0 beta 6

### ISSUE THREAD

**Issue by thebluepotato** [cezheng/Fuzi#28]
@cezheng Hi! The very recent Xcode update brought many changes to Swift 3.0, especially the end of implicitly bridged types and changes to pointers. Because the latter are heavily used in Fuzi, it won't compile. I tried fixing it myself but I really have trouble understanding how Swift handles pointers...

And a little heads up for you : they changed the whole "public/private" system and from what I've gathered from the release notes `open` is the old `public` and `fileprivate` is the old `private` : 
- A declaration marked as private can now only be accessed within the lexical scope it is declared in
(essentially the enclosing curly braces {}). A private declaration at the top level of a file can be
accessed anywhere in that file, as in Swift 2. The access level formerly known as private is now called
fileprivate. (SE-0025)
- Classes declared as public can no longer be subclassed outside of their defining module, and
methods declared as public can no longer be overridden outside of their defining module. To allow
a class to be externally subclassed or a method to be externally overridden, declare them as open,
which is a new access level beyond public.

**Comment by cezheng** [comment]
@thebluepotato 

Thanks for the information. Sorry I can't fix this immediately since I'm very busy with my work. Hopefully I would be able to lay my hands on it 2-3 days later. But if you somehow managed to deal with it before that, I'll be happy to review & merge your PR. Cheers.

**Comment by thebluepotato** [comment]
Actually it's compiling without complaints in my project but Alamofire hasn't been updated yet so the project as a whole doesn't compile yet. I'll try to fork the project and fix it myself. If I succeed, I'll make a PR!
Cheers mate!

**Comment by thebluepotato** [comment]
See PR https://github.com/cezheng/Fuzi/pull/29

**Comment by thebluepotato** [comment]
#29 merged!
