### ISSUE TITLE
Iterate Text Nodes

### ISSUE THREAD

**Issue by bytepoets-dan** [cezheng/Fuzi#3]
Hey!

Is there a possibility to also have text nodes when iterating over the children of a XMLElement? Right now we use xpath with the //text() selector for this.

br
denis

**Comment by cezheng** [comment]
@bytepoets-dan Hi, thanks for the feedback. I will appreciate it if you could provide a little bit more details on your use case(like a sample xml and a few lines of code) , so that I can better understand your issue.

I guess you might have a XML node that has element nodes and text nodes mixed right?

**Comment by bytepoets-dan** [comment]
Hey there,

Exactly, i have a node which has text and element nodes mixed together.

We are writing a parser and need to combine text and other nodes together according to certain criteria. If we iterate the children with element.xpath("node()"), the memory usage goes through the roof. This is not happening when iterating children of XMLElement. But with the latter we don't have access to the text nodes.

Any suggestions how to solve this problem?

br
denis

**Comment by cezheng** [comment]
Hello. I see your problem, and I will need to change the implementation to add a option allowing access to text node. Maybe this weekend if I get some free time.

**Comment by bytepoets-dan** [comment]
Hey, thanks! That would be awesome! :star2:

**Comment by cezheng** [comment]
@bytepoets-dan 
Hello, I have released Fuzi 0.3.0 allowing access to all types of nodes. You can now access text node children like this 

```
// child nodes typed Element and Text
parent.childNodes(ofTypes: [.Element, .Text])
```

for a list of node types refer to this file: https://github.com/cezheng/Fuzi/blob/master/Fuzi/Node.swift#L30

br😄

**Comment by bytepoets-dan** [comment]
@cezheng 

Wow, that was fast! 😄 I'm gonna try it today and report back to you. Many thaks for taking the time to make this happen. You sir are awesome! :+1: :star2: 

br
denis

**Comment by cezheng** [comment]
@bytepoets-dan Hello, I would appreciate it if you would let me know if the memory usage problem in your use case has been resolved or not. Thanks

**Comment by cezheng** [comment]
As I believe this issue is resolved & the issue reporter@bytepoets-dan is currently inactive on github to give me any feedback, I'm closing this issue.
