### ISSUE TITLE
dyld: Library not loaded: @rpath/Fuzi.framework/Fuzi

### ISSUE THREAD

**Issue by androidcn** [cezheng/Fuzi#35]
error:
dyld: Library not loaded: @rpath/Fuzi.framework/Fuzi
  Referenced from: /Users/xxx/Library/Developer/Xcode/DerivedData/marksix-ccpkaihhjxcprxalsglvfbucokfl/Build/Products/Debug-iphonesimulator/xxxx.framework/markSixKit
  Reason: image not found
(lldb) 

swift 3.0
Xcode 8

cocoapods

**Comment by cezheng** [comment]
No one know what you've done wrong if you don't share your project setup, cocoapods setup etc. I have created a project using cocoapods using the Podfile just like the README and it is working totally fine. The master branch is almost the same as the previous swift-3 branch which people have been using it for months.

**Comment by androidcn** [comment]
Sorry!
cocoapods 
    platform :ios, '9.0'

target ‘marksix’ do
	use_frameworks!
	pod 'LNRSimpleNotifications'
	pod 'SwiftyStoreKit'
	pod 'Google-Mobile-Ads-SDK', '~> 7.0’
end

target 'markSixKit' do
	use_frameworks!
	pod 'Fuzi'
end

**Comment by cezheng** [comment]
I guess you might have modified the cocoapods settings of your xcodeproj that makes the embedded frameworks not copied to the bundle correctly. Try creating an empty project using the same Podfile.

Also, you need to use Cocoapods 1.1.0+ for Xcode 8

**Comment by androidcn** [comment]
Thanks @cezheng 

update 1.1.0
sudo gem install cocoapods --pre

and then 

pod update


work now!
