### ISSUE TITLE
Does Fuzi let me automate the login process?

### ISSUE THREAD

**Issue by MasterSwift** [cezheng/Fuzi#36]
I can see that it parses html.

**Comment by cezheng** [comment]
Sure, Fuzi does let you automate the login process by making it easier for you to parse HTML, you just need to implement the login process logic yourself.

**Comment by MasterSwift** [comment]
do you have an example of this being implemented? I have used python selenium but it pretty much babysits you

**Comment by cezheng** [comment]
No Fuzi does not babysit you, it's just a parser. Think of it as nokogiri in Swift

**Comment by muescha** [comment]
you can use Alamofire to do the login stuff 

see an Ono Implementation:
https://github.com/Alamofire/Alamofire#creating-a-custom-response-serializer
