### ISSUE TITLE
Page not Found for swift 3.0

### ISSUE THREAD

**Issue by spynet** [cezheng/Fuzi#39]
Hi,
[Swift 3.0](https://github.com/cezheng/Fuzi/tree/swift-3) 
i am trying to access the above link it shows me a page not found please do the needful
Folk.

**Comment by cezheng** [comment]
swift 3.0 is master now https://github.com/cezheng/Fuzi/tree/master

I guess that link is something I forgot to modify. Where did you see that link?

**Comment by cezheng** [comment]
oh, it's the README for swift2.3 branch right? I have fixed the broken links. Thanks for reporting.

**Comment by spynet** [comment]
Thanks , now i am doing my works in pod file ,   

> pod 'Fuzi', '~> 1.0.0'

  am i using the correct one ?
Thanks in advance .

**Comment by cezheng** [comment]
@spynet 
Yes, 1.0.0 for Swift 3, 0.4.0 for Swift 2.3
