### ISSUE TITLE
Framework issues

### ISSUE THREAD

**Issue by amosavian** [cezheng/Fuzi#43]
Hi,
I added framework to my project manually but had some issues:

1. I had to add `libxml2.tbd` to framework

2. It had only macOS framework. There is not one for iOS, etc. Every os should have separate framework

3. It's not updated for Xcode 8.1 (recommended settings)

**Comment by cezheng** [comment]
@amosavian  Hi, may I know what package manager are you using? Thanks

**Comment by amosavian** [comment]
Hi, Thanks for response.
I manually added `Fuzi.xcodeproj` to my project.
I can make a pull request if it's okay.

**Comment by cezheng** [comment]
@amosavian 
https://github.com/cezheng/Fuzi#manually
As the README of this repo has stated, if you manually add it you do need to link libxml2 yourself(either adding libxml2.tbd or adding -lxml2 to Other Linker Flags)

As for the target, the current single Target should work for all platforms. It used to have 4 targets, but I reduced it to only 1 in this commit: https://github.com/cezheng/Fuzi/commit/21fec230924f56ec5288c576e68e51ba21caee67

**Comment by amosavian** [comment]
When I can add `xcodeproj` easily why I should bother adding sources?
I will make a pull request to rectify this issue asap

**Comment by cezheng** [comment]
@amosavian 
I guess Fuzi is linking -lxml2 with this module map. https://github.com/cezheng/Fuzi/blob/master/libxml2/module.modulemap

And adding the project work pretty much the same as using Carthage to build the framework and then adding the framework. For Carthage's case, it would only need to add Header Search Path for libxml2, so I'm not really sure why you need to add libxml2.tbd.

If you look at the FuziDemo project, it has the same structure of your project, and it adds neither libxml2.tbd nor -lxml2 flag, so I guess the problem is else where.

**Comment by amosavian** [comment]
I guess it's because you set `Always Search User Paths` to "NO". By the way that's not the standard way for a framework. As you mentioned we have either link it statically(-l flag) or dynamically(.tbd).

**Comment by cezheng** [comment]
@amosavian What do you mean by the 'standard way for a framework'? Setting `Always Search User Paths` to 'YES' will just make '#include <...>' work for User Search Paths, but I don't think it is correct to mess User Search Paths with System Search Paths, and the libxml2's include directory is definitely in System Search Paths.

**Comment by amosavian** [comment]
Hey @cezheng there is an issue for Info.plist copying in build phase

**Comment by cezheng** [comment]
oh? What is that?

**Comment by amosavian** [comment]
<img width="257" alt="screen shot 1395-09-13 at 10 43 10" src="https://cloud.githubusercontent.com/assets/6725192/20857562/564f2f6c-b945-11e6-8a48-3d30146f60b7.png">

**Comment by cezheng** [comment]
@amosavian can you show me the whole message?

**Comment by amosavian** [comment]
Removing Info.plist from here would resolve issue

<img width="757" alt="screen shot 1395-09-13 at 11 03 17" src="https://cloud.githubusercontent.com/assets/6725192/20857668/4357c7ea-b948-11e6-9531-e4c34c1b3dc1.png">

**Comment by tinygamefactory** [comment]
I tried to use this framework but failed in making it build with my project.  I followed the steps in manually installing it but then I get a compile error: 'libxml/xmlversion.h' file not found in xmlreader.h, Could not build Objective-C module 'libxml2'
When I followed the Carthage instructions the module simply could not be found.  Too bad, was looking forward to using xpath in swift.

**Comment by cezheng** [comment]
@tinygamefactory I don't think you did as the README says, since clearly the error message suggests that you didn't set the Header Search Path
