### ISSUE TITLE
How to get all html, and html from node element

### ISSUE THREAD

**Issue by Arti3DPlayer** [cezheng/Fuzi#5]
I want to write my html page to file like:
```
do {
   try HTMLDocument(string: NSString(data: responseData, encoding: NSUTF8StringEncoding) as! String, encoding: NSUTF8StringEncoding).allhtml!.stringValue.writeToFile(filename, atomically: true, encoding: NSUTF8StringEncoding)
} catch {}
```

But how to write full file?

And how to get all html from node like this:
```
for node in doc.xpath(xpath) {
            node.HTML_with_text
}
```

Is this possible ?

**Comment by cezheng** [comment]
Hello. @Arti3DPlayer .

First for your code you don't have to convert NSData to String. And your code will write the string that removes all the html tags into the file.

```
do {
   try HTMLDocument(data: responseData).body!.stringValue.writeToFile(filename, atomically: true, encoding: NSUTF8StringEncoding)
} catch {}
```

But what do you mean by write full file? If you have the full file data as NSData, just save the NSData to a file and you don't even have to use Fuzi.

for getting the full XML/HTML text with tags, use rawXML property

```
node.rawXML
```

**Comment by Arti3DPlayer** [comment]
thanks

**Comment by cezheng** [comment]
@Arti3DPlayer Sorry I don't quite get you, so let's take a look at this simple HTML. Which part of it do you want?
```
<!DOCTYPE html>
<html>
<head>
    <title>Which part do you want?</title>
</head>
<body>
<h1>Hello</h1>
<p>hi</p>
</body>
</html>
```

**Comment by Arti3DPlayer** [comment]
yes, it's what i want. Thanks
