### ISSUE TITLE
Anchor tag with table in it produces incorrect XMLElement.

### ISSUE THREAD

**Issue by niilohlin** [cezheng/Fuzi#52]
### Description:
* Expected behaviour:
```swift
do {
    var string = "<a href=\"/something.pdf\"><table>click here to go to pdf</table></a>"
    let document = try HTMLDocument(string: string)
    print(document.body!)
} catch let error {
    print(error)
}
```
should print
```html
<body>
<a href="/nothing.pdf"><table>click here to go to pdf</table></a>
</body>
```
* Actual behaviour:
prints
```html
<body>
<a href="/nothing.pdf"></a><table>click here to go to pdf</table>
</body>
```
### Environment
* Package Manager:
	- [x ] Carthage, version: 0.12.0
	- [ ] CocoaPods, version:
	- [ ] Manually

* Fuzi version: master
* Xcode version: 8.2.1

### How to reproduce:
See above. I know that this is very much an edge case. And probably by design. According to the [HTML5](https://www.w3.org/TR/html5/text-level-semantics.html#the-a-element) standard: _The a element may be wrapped around entire paragraphs, lists, tables, and so forth, even entire sections, so long as there is no interactive content within (e.g. buttons or other links)._
The code acts as expected when you wrap it in a div or a p tag. It's only the a tag that messes up.

**Comment by cezheng** [comment]
I guess libxml2 is implemented following HTML 4, and table tag inside anchor is not valid in HTML 4.

http://stackoverflow.com/a/6013974/1972061

**Comment by niilohlin** [comment]
Ok. Thank you. I'm probably not going to try to update libmxl2 for this one edge case in my test code.
