### ISSUE TITLE
Please support watchOS

### ISSUE THREAD

**Issue by androidcn** [cezheng/Fuzi#55]
Please support watchOS

**Comment by cezheng** [comment]
It is supported.

**Comment by androidcn** [comment]
![issue]
(http://i.imgur.com/fPTJ29e.png)

**Comment by cezheng** [comment]
Could you shared more details? I guess I have a issue template with all the information I want but you just did not use it

**Comment by androidcn** [comment]
no more detail...
just use fuzi api... in two framework one file

**Comment by cezheng** [comment]
Please look at the issue when you create new issues. There're many information I need to know. Like how do you integrate Fuzi, what package manager you are using, etc. Without those no one can help you. If you have info you do not want to share, just check the README and do as it says. Thousands of developers have been using it on various platforms and it is working so far so good.

**Comment by androidcn** [comment]
dyld: Library not loaded: @rpath/Fuzi.framework/Fuzi
  Referenced from: */*/*/*/*/*/Build/Products/Debug-watchsimulator/markSixKit_watchOS.framework/markSixKit_watchOS
  Reason: image not found

**Comment by androidcn** [comment]
please fix it

**Comment by cezheng** [comment]
What you provided is just an error message in your runtime which is completely useless.

If you create a new watchOS project and add Fuzi to it, it just works. So there must be something you did wrong when you add it to your project. But you are not sharing any information about your project with me.

Do you understand English? Or are you just using translation tools? I have asked you to look at the issue template.
