### ISSUE TITLE
Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1

### ISSUE THREAD

**Issue by Mr-GaoSai** [cezheng/Fuzi#58]
Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1

**Comment by cezheng** [comment]
I'm very busy at the moment so I would appreciate it if someone can open up a PR for this. Usually build error due to Swift version upgrade can be easily resolved by following the error messages in Xcode.

**Comment by SamuelZhaoY** [comment]
You get this error because you build the previous Fuzi module in old versions of Xcode and you made an upgrade of Xcode and hence the version of swift is also updated. To solve this, try carthage update Fuzi to rebuild the project?

**Comment by cezheng** [comment]
@Mr-GaoSai Please try as @SamuelZhaoY suggested
