### ISSUE TITLE
Error in HTML parsing

### ISSUE THREAD

**Issue by Xpymet** [cezheng/Fuzi#59]
Hello!
I have encountered an error when I attempt to parse this  piece of page:
```
...
<i>
    <p class="center">Тут должен быть текст на кириллице. Много текста.<br>
    <br>
    И здесь еще чуть чуть.
    <br>
    </p>
</i>
...
```

And after using:

`let doc = try HTMLDocument(string: mainHTMLFile, encoding: .utf8)`

The resulting nodes look like that:

```
...
<i></i>
<p class="center">Тут должен быть текст на кириллице. Много текста.<br>
<br>
И здесь еще чуть чуть.
<br>
</p>
...
```
 
Using Swift, Xcode 8.3.2, pod 'Fuzi', '~> 1.0.0'

**Comment by cezheng** [comment]
Seems like an encoding problem. Generally, prefer HTMLDocument(data:) over HTMLDocument(string:, encoding:) since the former way you don't have to know the encoding.
