### ISSUE TITLE
Remove element

### ISSUE THREAD

**Issue by dev4dev** [cezheng/Fuzi#68]
Hello, is there any way to add ability to remove Element from document tree?

I tried to add some code
```swift
	open func remove() {
		xmlUnlinkNode(cNode)
		xmlFreeNode(cNode)
	}
```
to XMLElement. But it does nothing. Content remains the same

**Comment by cezheng** [comment]
This seems a pure libxml question which is out of scope for Fuzi. You may refer to libxml's [documentation](http://xmlsoft.org/html/index.html).
