### ISSUE TITLE
Issues on Swift 4.

### ISSUE THREAD

**Issue by bernikowich-cedoni** [cezheng/Fuzi#69]
### Environment
* Fuzi version: 2.0.0
* Xcode version: 9.0

### How to reproduce:
Compile any Swift 4 project. Issues with ```rangeAt(1)``` / ```range(at: 1)```.

**Comment by cezheng** [comment]
what do you mean by Issues with rangeAt(1) / range(at: 1) ? travis build is passing

**Comment by zkrige** [comment]
same issue here

see screenshot
<img width="383" alt="screen shot 2017-10-16 at 14 14 26" src="https://user-images.githubusercontent.com/968412/31611435-5a9c588e-b27c-11e7-8488-ea4aec130619.png">

**Comment by zkrige** [comment]
#72 fixes

**Comment by cezheng** [comment]
Your PR does not build with travis. I'm pretty sure for Swift 3 it was rangeAt(_:) and then it was changed to range(at:) in Swift 4, which is stated clearly in the screenshot.

Please check your project's setting

**Comment by cezheng** [comment]
I would confirm this as a misconfiguration of Swift version. Closing this issue.
