### ISSUE TITLE
Swift Compiler Error: No such module "libxml2"

### ISSUE THREAD

**Issue by candeladiao** [cezheng/Fuzi#85]
### Description: 
Header Search Paths: $(SDKROOT)/usr/include/libxml2
Other Linker Flags: -lxml2

* Expected behaviour:

* Actual behaviour:
Element.swift: No such module "libxml2"

### Environment
* Package Manager:
	- [ ] Carthage, version:
	- [ ] CocoaPods, version:
	- [ ] Manually

* Fuzi version:master
* Xcode version:9.2

**Comment by candeladiao** [comment]
import paths: $(SRCROOT)/libxml2

/*libxml2*/
libxml2.h
module.modulemap

/*libxml2.h*/
#import <libxml2/libxml/xmlreader.h>
#import <libxml2/libxml/xpath.h>
#import <libxml2/libxml/xpathInternals.h>
#import <libxml2/libxml/HTMLparser.h>
#import <libxml2/libxml/HTMLtree.h>

/*module.modulemap*/
module libxml2 [system] {
  link "xml2"
  umbrella header "libxml2-fuzi.h"
  export *
  module * { export * }
}

**Comment by cezheng** [comment]
Please use the latest Xcode(9.3) for latest Fuzi(2.0.2).

For Xcode 9.2 please use Fuzi 2.0.1
