### ISSUE TITLE
Please release a new CocoaPod version

### ISSUE THREAD

**Issue by kukushi** [cezheng/Fuzi#93]
### Description:
* Expected behaviour:

* Actual behaviour:

### Environment
* Package Manager:
	- [ ] Carthage, version:
	- [x] CocoaPods, version:
	- [ ] Manually

* Fuzi version: 2.1.0
* Xcode version: 10.2

### How to reproduce:
Build with the 10.2

**Comment by kosicki123** [comment]
Carthage is also not working, the project is not building. Needs to conforme NodeSet to Sequence. No idea how to do that.

**Comment by DavidLari** [comment]
I had to change _precondition to precondition, but that got it building in 4.2 mode.

**Comment by DavidLari** [comment]
Also, to build in Swift 5 mode, just two open lets have to be changed to public.

**Comment by JohnnyTseng** [comment]
For whoever having issues building on Xcode 10.2, there is a workaround for this.
Install `Fuzi` in Podfile using this 

`
pod 'Fuzi', :git => 'git@github.com:cezheng/Fuzi.git', :branch => 'master'
`

Because the latest 2.1.0 tag does not contains the fix of this issue, but master does.

**Comment by miguelangelnet** [comment]
I was going to make a PR helping for the new Swift 5 version, but, looks like with Swift 5 and the modifications already in master there is issues parsing data (few HTML unit tests are failing), so, looks like it's not ready. If someone use the master branch right now for Swift 5, please, check what I said been sure nothing is broken in your environment.

I'm trying to hep with the issues, but I don't know when I can have something.

**Comment by cezheng** [comment]
Thanks for filing the issue. I will probably spend sometime this weekend (pacific time) to fix this, or I will happily review any PR if anyone is already actively working on a fix.

**Comment by cezheng** [comment]
[2.2.1](https://github.com/cezheng/Fuzi/releases/tag/2.2.1) for Swift 4.2 and [3.0.0](https://github.com/cezheng/Fuzi/releases/tag/3.0.0) for Swift 5.0 have been released.
