### ISSUE TITLE
isHTML returns false for HTML nodes

### ISSUE THREAD

**Issue by laurent-humbert** [cezheng/Fuzi#95]
let html2 = "<html><head></head><body>SOME TEXT</body></html>"
        let doc2 = try? HTMLDocument(string: html2)!
        theBody2 = doc2.body
        print("isHTML", theBody2.isHTML)

       this prints "FALSE"

      then rawXML calls xmlNodeDump instead of htmlNodeDump which in my case is bad.

### Environment
* Package Manager:
	- [ ] Carthage, version:
	- [ ] CocoaPods, version:
	- [ x] Manually

* Fuzi version: Latest
* Xcode version: 10.2

### How to reproduce:

**Comment by cezheng** [comment]
Thanks for filing the issue. This bug is fixed in 2.2.1 for Swift 4.2 and 3.0.0 for Swift 5.0.

**Comment by laurent-humbert** [comment]
Outstanding. Thank you!
