### ISSUE TITLE
While installing through Carthage it should  downloads version "3.0.0", but it installs "2.1.0" help wanted

### ISSUE THREAD

**Issue by arunlj561** [cezheng/Fuzi#97]
### Description:
* Expected behaviour:
While installing through Carthage it should  downloads version "3.0.0", but it installs "2.1.0"

* Actual behaviour:

While installing through Carthage it downloads version "2.1.0", but i want to install "3.0.0"
carthage update
*** Fetching Kingfisher
*** Fetching r2-shared-swift
*** Fetching r2-streamer-swift
*** Fetching readium-opds-swift
*** Fetching ZIPFoundation
*** Fetching r2-navigator-swift
*** Fetching AEXML
*** Fetching Minizip
*** Fetching CryptoSwift
*** Fetching SQLite.swift
*** Fetching MBProgressHUD
*** Fetching GCDWebServer
*** Fetching Fuzi
*** Fetching r2-shared-swift
*** Fetching r2-shared-swift
*** Fetching r2-shared-swift
*** Checking out ZIPFoundation at "5e0ea3a0d5f5e57dbd3822076621403932859f53"
*** Checking out Fuzi at "2.1.0"
*** Checking out r2-shared-swift at "c01177ff01bf52b6722b2842a53485b4a9781790"
*** Checking out MBProgressHUD at "1.1.0"
*** Checking out readium-opds-swift at "88606fbfc57f854e9e2eaad67d351f9c16facac8"
*** Checking out Kingfisher at "4.6.4"
*** Checking out Minizip at "1.4.0"
*** Checking out r2-streamer-swift at "1cc6dc1c683b12592b052c80669302f9c36efcdd"
*** Checking out AEXML at "4.3.3"
*** Checking out SQLite.swift at "0.11.5"
*** Checking out r2-navigator-swift at "74acf9fc8ad3ccbc0c5c7f3127aabb01e80d6a70"
*** Checking out GCDWebServer at "3.5.2"
*** Checking out CryptoSwift at "0.14.0"
*** xcodebuild output can be found in /var/folders/hl/q7jgr_hs3db5vckgl575rbp40000gn/T/carthage-xcodebuild.HFmjSe.log
*** Building scheme "AEXML macOS" in AEXML.xcodeproj
*** Building scheme "AEXML watchOS" in AEXML.xcodeproj
*** Building scheme "AEXML iOS" in AEXML.xcodeproj
*** Building scheme "AEXML tvOS" in AEXML.xcodeproj
*** Building scheme "CryptoSwift" in CryptoSwift.xcworkspace
*** Building scheme "Fuzi" in Fuzi.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/arunjangid/Downloads/r2-testapp-swift-develop/Carthage/Checkouts/Fuzi/Fuzi.xcworkspace -scheme Fuzi -configuration Release -derivedDataPath /Users/arunjangid/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/Fuzi/2.1.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/hl/q7jgr_hs3db5vckgl575rbp40000gn/T/Fuzi SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/arunjangid/Downloads/r2-testapp-swift-develop/Carthage/Checkouts/Fuzi)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/hl/q7jgr_hs3db5vckgl575rbp40000gn/T/carthage-xcodebuild.HFmjSe.log

**xcodebuild log** 

/Users/arunjangid/Downloads/r2-testapp-swift-develop/Carthage/Checkouts/Fuzi/Sources/Node.swift:91:20: warning: 'let' properties are implicitly 'final'; use 'public' instead of 'open'
  open unowned let document: XMLDocument
  ~~~~             ^
  public
/Users/arunjangid/Downloads/r2-testapp-swift-develop/Carthage/Checkouts/Fuzi/Sources/NodeSet.swift:104:19: warning: static declarations are implicitly 'final'; use 'public' instead of 'open'
  open static let emptySet = XPathNodeSet(cXPath: nil, document: nil)
  ~~~~            ^
  public
/Users/arunjangid/Downloads/r2-testapp-swift-develop/Carthage/Checkouts/Fuzi/Sources/NodeSet.swift:77:5: error: use of unresolved identifier '_precondition'; did you mean 'precondition'?
    _precondition(idx >= startIndex && idx < endIndex, "Index of out bound")
    ^~~~~~~~~~~~~
    precondition
Swift.precondition:1:13: note: 'precondition' declared here
public func precondition(_ condition: @autoclosure () -> Bool, _ message: @autoclosure () -> String = String(), file: StaticString = #file, line: UInt = #line)
            ^

** ARCHIVE FAILED **



### Environment
* Package Manager:
	- [ ] Carthage, version: 2.1.0
	- [ ] CocoaPods, version: NA
	- [ ] Manually

* Fuzi version: 2.1.0
* Xcode version: 10.2

### How to reproduce:
Try steps given above

**Comment by cezheng** [comment]
This is just an Carthage usage issue, you can specify any version you want in the Cartfile
