### ISSUE TITLE
xpath can not get right results with Xcode 10.2.1

### ISSUE THREAD

**Issue by stevema** [cezheng/Fuzi#98]
### Environment
* Package Manager:
	- [ ] Carthage, version:
	- [ ] CocoaPods, version:1.7.0.beta.3
	- [ ] Manually

* Fuzi version:1.0.1
* Xcode version:10.2.1

### How to reproduce:

let doc = try HTMLDocument(string: html)
let titleXpath = "//html/body/center/form/div[1]/div/table//td[@class='f_title']//a[@href]"
let titleItem = doc.xpath(titleXpath)

when use Xcode 10.1, titleItem has the right results,but the same codes in Xcode 10.2.1,titleItem is empty

**Comment by cezheng** [comment]
Would you please also share the HTML that produced the wrong results so that I can actually reproduce? Thanks!

**Comment by cezheng** [comment]
Also, I realized you are using version 1.0.1 which is not supposed to work with any version after Swift 3.x. Please update to the latest version and try again.

**Comment by stevema** [comment]
> Also, I realized you are using version 1.0.1 which is not supposed to work with any version after Swift 3.x. Please update to the latest version and try again.

Thanks a lot, it's solved after update.
